FROM golang:1.22-alpine AS builder

RUN apk add --no-cache git
RUN git clone --depth 1 https://github.com/slotopol/server.git /build
WORKDIR /build
RUN go build -o /slotopol-server ./cmd/server

FROM alpine:3.19
COPY --from=builder /slotopol-server /usr/local/bin/slotopol-server
EXPOSE 8080
CMD ["slotopol-server"]
