"""initial

Revision ID: b03cfc59671b
Revises: 
Create Date: 2026-02-16 11:49:10.358810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b03cfc59671b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casinos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('description_pt', sa.Text(), nullable=True),
    sa.Column('description_es', sa.Text(), nullable=True),
    sa.Column('min_deposit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pix_supported', sa.Boolean(), nullable=False),
    sa.Column('spei_supported', sa.Boolean(), nullable=False),
    sa.Column('crypto_supported', sa.Boolean(), nullable=False),
    sa.Column('withdrawal_time', sa.String(length=100), nullable=True),
    sa.Column('affiliate_program', sa.String(length=100), nullable=True),
    sa.Column('affiliate_link_template', sa.Text(), nullable=True),
    sa.Column('ref_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('geo', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('geo', sa.String(length=5), nullable=False),
    sa.Column('preferred_games', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('preferred_deposit', sa.String(length=50), nullable=True),
    sa.Column('preferred_payment', sa.String(length=50), nullable=True),
    sa.Column('jogai_coins', sa.Integer(), nullable=False),
    sa.Column('is_pro', sa.Boolean(), nullable=False),
    sa.Column('pro_expires_at', sa.DateTime(), nullable=True),
    sa.Column('referred_by', sa.BigInteger(), nullable=True),
    sa.Column('referral_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referred_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_code')
    )
    op.create_index('idx_users_geo', 'users', ['geo'], unique=False)
    op.create_index('idx_users_locale', 'users', ['locale'], unique=False)
    op.create_index('idx_users_referral_code', 'users', ['referral_code'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('input_type', sa.String(length=20), nullable=False),
    sa.Column('parsed_bonus_percent', sa.Integer(), nullable=True),
    sa.Column('parsed_wagering', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('parsed_deadline', sa.Integer(), nullable=True),
    sa.Column('parsed_max_bet', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('jogai_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('verdict_key', sa.String(length=50), nullable=True),
    sa.Column('ai_response', sa.Text(), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('casino_id', sa.Integer(), nullable=True),
    sa.Column('game_type', sa.String(length=50), nullable=True),
    sa.Column('game_name', sa.String(length=255), nullable=True),
    sa.Column('bet_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bet_currency', sa.String(length=5), nullable=False),
    sa.Column('result_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['casino_id'], ['casinos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bonuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('casino_id', sa.Integer(), nullable=True),
    sa.Column('title_pt', sa.String(length=500), nullable=True),
    sa.Column('title_es', sa.String(length=500), nullable=True),
    sa.Column('bonus_percent', sa.Integer(), nullable=True),
    sa.Column('max_bonus_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_bonus_currency', sa.String(length=5), nullable=False),
    sa.Column('wagering_multiplier', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('wagering_deadline_days', sa.Integer(), nullable=True),
    sa.Column('max_bet', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('free_spins', sa.Integer(), nullable=False),
    sa.Column('no_deposit', sa.Boolean(), nullable=False),
    sa.Column('jogai_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('verdict_key', sa.String(length=50), nullable=True),
    sa.Column('expected_loss', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit_probability', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('affiliate_link', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('geo', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['casino_id'], ['casinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bonuses_active_geo', 'bonuses', ['is_active', 'geo'], unique=False, postgresql_where=sa.text('is_active IS true'))
    op.create_index('idx_bonuses_score', 'bonuses', [sa.text('jogai_score DESC')], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('referrer_id', sa.BigInteger(), nullable=True),
    sa.Column('referred_id', sa.BigInteger(), nullable=True),
    sa.Column('coins_awarded', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referred_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sport_picks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_name', sa.String(length=500), nullable=True),
    sa.Column('league', sa.String(length=100), nullable=True),
    sa.Column('pick_description_pt', sa.Text(), nullable=True),
    sa.Column('pick_description_es', sa.Text(), nullable=True),
    sa.Column('odds', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('analysis_pt', sa.Text(), nullable=True),
    sa.Column('analysis_es', sa.Text(), nullable=True),
    sa.Column('casino_id', sa.Integer(), nullable=True),
    sa.Column('affiliate_link', sa.Text(), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('match_date', sa.DateTime(), nullable=True),
    sa.Column('geo', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['casino_id'], ['casinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sport_picks_geo', 'sport_picks', ['geo'], unique=False)
    op.create_table('clicks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('bonus_id', sa.Integer(), nullable=True),
    sa.Column('casino_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bonus_id'], ['bonuses.id'], ),
    sa.ForeignKeyConstraint(['casino_id'], ['casinos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_clicks_locale', 'clicks', ['locale'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content_pt', sa.Text(), nullable=True),
    sa.Column('content_es', sa.Text(), nullable=True),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('bonus_id', sa.Integer(), nullable=True),
    sa.Column('casino_id', sa.Integer(), nullable=True),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_channel', sa.String(length=50), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('geo', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['bonus_id'], ['bonuses.id'], ),
    sa.ForeignKeyConstraint(['casino_id'], ['casinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_posts_geo', 'posts', ['geo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_posts_geo', table_name='posts')
    op.drop_table('posts')
    op.drop_index('idx_clicks_locale', table_name='clicks')
    op.drop_table('clicks')
    op.drop_index('idx_sport_picks_geo', table_name='sport_picks')
    op.drop_table('sport_picks')
    op.drop_table('referrals')
    op.drop_index('idx_bonuses_score', table_name='bonuses')
    op.drop_index('idx_bonuses_active_geo', table_name='bonuses', postgresql_where=sa.text('is_active IS true'))
    op.drop_table('bonuses')
    op.drop_table('bets')
    op.drop_table('analyses')
    op.drop_index('idx_users_referral_code', table_name='users')
    op.drop_index('idx_users_locale', table_name='users')
    op.drop_index('idx_users_geo', table_name='users')
    op.drop_table('users')
    op.drop_table('casinos')
    # ### end Alembic commands ###
