import asyncio
from datetime import datetime, timedelta

from sqlalchemy import select

from app.database.engine import async_session
from app.database.models import Bonus, Casino, SportPick


async def seed():
    async with async_session() as session:
        # Check if already seeded
        result = await session.execute(select(Casino).limit(1))
        if result.scalar():
            print("Database already seeded, skipping.")
            return

        # --- Casinos ---
        casinos = [
            Casino(
                name="PIN-UP",
                slug="pinup",
                logo_url="https://jogai.fun/img/pinup.png",
                description_pt="PIN-UP é uma das maiores plataformas de apostas e cassino online da América Latina. Oferece slots, jogos ao vivo, apostas esportivas e bônus generosos.",
                description_es="PIN-UP es una de las mayores plataformas de apuestas y casino online de América Latina.",
                min_deposit=20.00,
                min_deposits={"BRL": 20.0, "MXN": 400.0},
                pix_supported=True,
                spei_supported=True,
                crypto_supported=True,
                withdrawal_time="1-24h",
                affiliate_program="PIN-UP Partners",
                affiliate_link_template="https://pinup.com/?ref={ref_id}&uid={user_id}",
                ref_id="jogai_12345",
                is_active=True,
                geo=["BR", "MX"],
            ),
            Casino(
                name="1WIN",
                slug="1win",
                logo_url="https://jogai.fun/img/1win.png",
                description_pt="1WIN oferece mais de 10.000 slots, cassino ao vivo e apostas esportivas com odds competitivas. Saque rápido via PIX.",
                description_es="1WIN ofrece más de 10,000 slots, casino en vivo y apuestas deportivas con cuotas competitivas.",
                min_deposit=10.00,
                min_deposits={"BRL": 10.0, "MXN": 200.0},
                pix_supported=True,
                spei_supported=True,
                crypto_supported=True,
                withdrawal_time="1-12h",
                affiliate_program="1WIN Partners",
                affiliate_link_template="https://1win.com/?ref={ref_id}&uid={user_id}",
                ref_id="jogai_67890",
                is_active=True,
                geo=["BR", "MX"],
            ),
            Casino(
                name="BET365",
                slug="bet365",
                logo_url="https://jogai.fun/img/bet365.png",
                description_pt="Bet365 é a maior casa de apostas do mundo. Cobertura completa de esportes, cassino ao vivo e odds competitivas com saque rápido via PIX.",
                description_es="Bet365 es la mayor casa de apuestas del mundo. Cobertura completa de deportes, casino en vivo y cuotas competitivas.",
                min_deposit=20.00,
                min_deposits={"BRL": 20.0, "MXN": 350.0},
                pix_supported=True,
                spei_supported=True,
                crypto_supported=False,
                withdrawal_time="1-24h",
                affiliate_program="Bet365 Affiliates",
                affiliate_link_template="https://bet365.com/?ref={ref_id}&uid={user_id}",
                ref_id="jogai_11111",
                is_active=True,
                geo=["BR", "MX"],
            ),
            Casino(
                name="RIVALO",
                slug="rivalo",
                logo_url="https://jogai.fun/img/rivalo.png",
                description_pt="Rivalo é uma plataforma focada na América Latina com apostas esportivas, cassino e promoções exclusivas para o Brasil.",
                description_es="Rivalo es una plataforma enfocada en América Latina con apuestas deportivas, casino y promociones exclusivas.",
                min_deposit=15.00,
                min_deposits={"BRL": 15.0, "MXN": 300.0},
                pix_supported=True,
                spei_supported=True,
                crypto_supported=False,
                withdrawal_time="1-24h",
                affiliate_program="Rivalo Affiliates",
                affiliate_link_template="https://rivalo.com/?ref={ref_id}&uid={user_id}",
                ref_id="jogai_22222",
                is_active=True,
                geo=["BR", "MX"],
            ),
        ]
        session.add_all(casinos)
        await session.flush()

        # --- Bonuses ---
        now = datetime.utcnow()
        bonuses = [
            Bonus(
                casino_id=casinos[0].id,
                title_pt="Bônus de Boas-Vindas 150% até R$1.500",
                title_es="Bono de Bienvenida 150% hasta MX$5,000",
                bonus_percent=150,
                max_bonus_amount=1500.00,
                max_bonus_currency="BRL",
                wagering_multiplier=35.0,
                wagering_deadline_days=30,
                max_bet=25.00,
                free_spins=250,
                jogai_score=8.5,
                verdict_key="verdict_excellent",
                expected_loss=350.00,
                profit_probability=32.00,
                affiliate_link="https://pinup.com/?ref=jogai_12345",
                is_active=True,
                starts_at=now,
                expires_at=now + timedelta(days=30),
                geo=["BR"],
            ),
            Bonus(
                casino_id=casinos[0].id,
                title_pt="Sexta Sem Risco — Cashback 10%",
                title_es="Viernes Sin Riesgo — Cashback 10%",
                bonus_percent=10,
                max_bonus_amount=500.00,
                max_bonus_currency="BRL",
                wagering_multiplier=5.0,
                wagering_deadline_days=7,
                max_bet=50.00,
                jogai_score=7.2,
                verdict_key="verdict_good",
                expected_loss=50.00,
                profit_probability=65.00,
                affiliate_link="https://pinup.com/?ref=jogai_12345",
                is_active=True,
                starts_at=now,
                expires_at=now + timedelta(days=7),
                geo=["BR"],
            ),
            Bonus(
                casino_id=casinos[1].id,
                title_pt="1WIN: 500% no primeiro depósito",
                title_es="1WIN: 500% en el primer depósito",
                bonus_percent=500,
                max_bonus_amount=5000.00,
                max_bonus_currency="BRL",
                wagering_multiplier=50.0,
                wagering_deadline_days=30,
                max_bet=15.00,
                jogai_score=5.0,
                verdict_key="verdict_caution",
                expected_loss=2800.00,
                profit_probability=12.00,
                affiliate_link="https://1win.com/?ref=jogai_67890",
                is_active=True,
                starts_at=now,
                expires_at=now + timedelta(days=60),
                geo=["BR"],
            ),
            Bonus(
                casino_id=casinos[1].id,
                title_pt="Rodadas Grátis — 70 Free Spins sem depósito",
                title_es="Giros Gratis — 70 Free Spins sin depósito",
                bonus_percent=0,
                max_bonus_amount=0,
                max_bonus_currency="BRL",
                wagering_multiplier=40.0,
                wagering_deadline_days=7,
                max_bet=5.00,
                free_spins=70,
                no_deposit=True,
                jogai_score=6.8,
                verdict_key="verdict_good",
                expected_loss=0,
                profit_probability=18.00,
                affiliate_link="https://1win.com/?ref=jogai_67890",
                is_active=True,
                starts_at=now,
                expires_at=now + timedelta(days=14),
                geo=["BR"],
            ),
            # BET365 bonuses
            Bonus(
                casino_id=casinos[2].id,
                title_pt="Bet365: Aposta Grátis de R$200 no primeiro depósito",
                title_es="Bet365: Apuesta Gratis de MX$1,000 en el primer depósito",
                bonus_percent=100,
                max_bonus_amount=200.00,
                max_bonus_currency="BRL",
                wagering_multiplier=3.0,
                wagering_deadline_days=30,
                max_bet=50.00,
                jogai_score=9.0,
                verdict_key="verdict_excellent",
                expected_loss=30.00,
                profit_probability=55.00,
                affiliate_link="https://bet365.com/?ref=jogai_11111",
                is_active=True,
                starts_at=now,
                expires_at=now + timedelta(days=30),
                geo=["BR"],
            ),
            Bonus(
                casino_id=casinos[2].id,
                title_pt="Bet365: Acumulador do Dia — Odds Turbinadas",
                title_es="Bet365: Acumulador del Día — Cuotas Mejoradas",
                bonus_percent=0,
                max_bonus_amount=0,
                max_bonus_currency="BRL",
                wagering_multiplier=1.0,
                wagering_deadline_days=1,
                max_bet=100.00,
                jogai_score=7.5,
                verdict_key="verdict_good",
                expected_loss=0,
                profit_probability=40.00,
                affiliate_link="https://bet365.com/?ref=jogai_11111",
                is_active=True,
                starts_at=now,
                expires_at=now + timedelta(days=7),
                geo=["BR"],
            ),
            # RIVALO bonuses
            Bonus(
                casino_id=casinos[3].id,
                title_pt="Rivalo: 100% até R$500 + 50 Free Spins",
                title_es="Rivalo: 100% hasta MX$2,500 + 50 Giros Gratis",
                bonus_percent=100,
                max_bonus_amount=500.00,
                max_bonus_currency="BRL",
                wagering_multiplier=30.0,
                wagering_deadline_days=21,
                max_bet=25.00,
                free_spins=50,
                jogai_score=7.8,
                verdict_key="verdict_good",
                expected_loss=180.00,
                profit_probability=35.00,
                affiliate_link="https://rivalo.com/?ref=jogai_22222",
                is_active=True,
                starts_at=now,
                expires_at=now + timedelta(days=30),
                geo=["BR"],
            ),
            Bonus(
                casino_id=casinos[3].id,
                title_pt="Rivalo: Freebet R$50 em apostas esportivas",
                title_es="Rivalo: Freebet MX$250 en apuestas deportivas",
                bonus_percent=0,
                max_bonus_amount=50.00,
                max_bonus_currency="BRL",
                wagering_multiplier=5.0,
                wagering_deadline_days=7,
                max_bet=50.00,
                jogai_score=8.2,
                verdict_key="verdict_excellent",
                expected_loss=10.00,
                profit_probability=60.00,
                affiliate_link="https://rivalo.com/?ref=jogai_22222",
                is_active=True,
                starts_at=now,
                expires_at=now + timedelta(days=14),
                geo=["BR"],
            ),
        ]
        session.add_all(bonuses)

        # --- MX Bonuses ---
        mx_bonuses = [
            # PIN-UP MX
            Bonus(
                casino_id=casinos[0].id,
                title_pt="PIN-UP: Bônus 150% até MX$30,000",
                title_es="PIN-UP: Bono de Bienvenida 150% hasta MX$30,000",
                bonus_percent=150,
                max_bonus_amount=30000.00,
                max_bonus_currency="MXN",
                wagering_multiplier=35.0,
                wagering_deadline_days=30,
                max_bet=500.00,
                free_spins=250,
                jogai_score=8.5,
                verdict_key="verdict_excellent",
                expected_loss=7000.00,
                profit_probability=32.00,
                affiliate_link="https://pinup.com/?ref=jogai_12345",
                is_active=True,
                starts_at=now,
                expires_at=now + timedelta(days=30),
                geo=["MX"],
            ),
            # 1WIN MX
            Bonus(
                casino_id=casinos[1].id,
                title_pt="1WIN: 500% no primeiro depósito (MX)",
                title_es="1WIN: 500% en tu primer depósito",
                bonus_percent=500,
                max_bonus_amount=100000.00,
                max_bonus_currency="MXN",
                wagering_multiplier=50.0,
                wagering_deadline_days=30,
                max_bet=300.00,
                jogai_score=5.0,
                verdict_key="verdict_caution",
                expected_loss=56000.00,
                profit_probability=12.00,
                affiliate_link="https://1win.com/?ref=jogai_67890",
                is_active=True,
                starts_at=now,
                expires_at=now + timedelta(days=60),
                geo=["MX"],
            ),
            # BET365 MX
            Bonus(
                casino_id=casinos[2].id,
                title_pt="Bet365: Aposta Grátis MX$1,000",
                title_es="Bet365: Apuesta Gratis de MX$1,000 en el primer depósito",
                bonus_percent=100,
                max_bonus_amount=1000.00,
                max_bonus_currency="MXN",
                wagering_multiplier=3.0,
                wagering_deadline_days=30,
                max_bet=1000.00,
                jogai_score=9.0,
                verdict_key="verdict_excellent",
                expected_loss=60.00,
                profit_probability=55.00,
                affiliate_link="https://bet365.com/?ref=jogai_11111",
                is_active=True,
                starts_at=now,
                expires_at=now + timedelta(days=30),
                geo=["MX"],
            ),
            # RIVALO MX
            Bonus(
                casino_id=casinos[3].id,
                title_pt="Rivalo: 100% até MX$5,000 + 50 Giros",
                title_es="Rivalo: 100% hasta MX$5,000 + 50 Giros Gratis",
                bonus_percent=100,
                max_bonus_amount=5000.00,
                max_bonus_currency="MXN",
                wagering_multiplier=30.0,
                wagering_deadline_days=21,
                max_bet=500.00,
                free_spins=50,
                jogai_score=7.8,
                verdict_key="verdict_good",
                expected_loss=3600.00,
                profit_probability=35.00,
                affiliate_link="https://rivalo.com/?ref=jogai_22222",
                is_active=True,
                starts_at=now,
                expires_at=now + timedelta(days=30),
                geo=["MX"],
            ),
        ]
        session.add_all(mx_bonuses)

        # --- Sport Picks ---
        sport_picks = [
            # BR pick
            SportPick(
                match_name="Flamengo vs Palmeiras",
                league="Brasileirão Série A",
                pick_description_pt="Flamengo em casa com elenco completo. Odds com valor no empate. Aposte via Bet365.",
                pick_description_es="Flamengo en casa con plantel completo. Cuotas con valor en empate. Apuesta vía Bet365.",
                odds=3.20,
                analysis_pt="Flamengo domina em casa (78% aproveitamento). Palmeiras sem 2 titulares. Histórico: últimos 5 jogos em casa — 4V 1E 0D. Recomendação: Empate ou Flamengo (Dupla Chance) na Bet365.",
                analysis_es="Flamengo domina en casa (78% aprovechamiento). Palmeiras sin 2 titulares. Recomendación: Empate o Flamengo (Doble Chance) en Bet365.",
                casino_id=casinos[2].id,
                affiliate_link="https://bet365.com/?ref=jogai_11111",
                match_date=now + timedelta(days=1),
                geo=["BR"],
            ),
            # MX pick — Liga MX
            SportPick(
                match_name="Club América vs Guadalajara",
                league="Liga MX",
                pick_description_pt="Clássico mexicano. América favorito em casa com odds de valor.",
                pick_description_es="El Clásico Nacional. América favorito en casa con cuotas de valor. Apuesta vía Bet365.",
                odds=2.10,
                analysis_pt="América domina em casa (80% aproveitamento na temporada). Guadalajara sem 3 titulares. Recomendação: América ou Empate (Dupla Chance) na Bet365.",
                analysis_es="América domina en casa (80% aprovechamiento en la temporada). Guadalajara sin 3 titulares. Historial: últimos 5 juegos en casa — 4V 1E 0D. Recomendación: América o Empate (Doble Chance) en Bet365.",
                casino_id=casinos[2].id,
                affiliate_link="https://bet365.com/?ref=jogai_11111",
                match_date=now + timedelta(days=1),
                geo=["MX"],
            ),
        ]
        for sp in sport_picks:
            session.add(sp)

        await session.commit()
        print("Seed complete: 4 casinos, 12 bonuses (8 BR + 4 MX), 2 sport_picks (1 BR + 1 MX)")


if __name__ == "__main__":
    asyncio.run(seed())
